/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseParametric;

import java.sql.*;
/**
 *
 * @author Chris
 */
public class DBparametric extends javax.swing.JFrame {

    /**
     * Creates new form DBparametric
     */
    public DBparametric() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cdtName = new javax.swing.JTextField();
        cdtStipend = new javax.swing.JTextField();
        cdtMajor = new javax.swing.JTextField();
        cdtGradYear = new javax.swing.JTextField();
        cdtAPFT = new javax.swing.JTextField();
        cdtHeight = new javax.swing.JTextField();
        cdtWeight = new javax.swing.JTextField();
        cdtCWST = new javax.swing.JCheckBox();
        cdtClearance = new javax.swing.JCheckBox();
        cdtCAC = new javax.swing.JCheckBox();
        cdtTags = new javax.swing.JCheckBox();
        cdtAviation = new javax.swing.JCheckBox();
        cdtContract = new javax.swing.JCheckBox();
        cdtMilHistory = new javax.swing.JCheckBox();
        parametric = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cdtName.setText("Name");

        cdtStipend.setText("Stipend");

        cdtMajor.setText("Major");

        cdtGradYear.setText("Grad Year");

        cdtAPFT.setText("APFT Score");

        cdtHeight.setText("Height");

        cdtWeight.setText("Weight");

        cdtCWST.setText("CWST");

        cdtClearance.setText("Clearance");

        cdtCAC.setText("Cac Card");

        cdtTags.setText("ID Tags");

        cdtAviation.setText("Aviation");

        cdtContract.setText("Contract");

        cdtMilHistory.setText("Mil History");

        parametric.setText("Parametric Console");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cdtStipend)
                            .addComponent(cdtName)
                            .addComponent(cdtAPFT)
                            .addComponent(cdtMajor)
                            .addComponent(cdtGradYear)
                            .addComponent(cdtHeight)
                            .addComponent(cdtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cdtMilHistory)
                            .addComponent(cdtContract)
                            .addComponent(cdtCWST, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdtClearance)
                            .addComponent(cdtCAC)
                            .addComponent(cdtTags)
                            .addComponent(cdtAviation)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(parametric)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(Submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(parametric)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdtMilHistory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdtStipend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdtContract))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdtCWST))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdtGradYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdtClearance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdtAPFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdtCAC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdtTags))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdtAviation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Submit)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        try{
            //1. Get a Connection
            Connection myConn = DriverManager.getConnection("jdbc:mysql://cs-database:3306/cmridgely1", "cmridgely1", "1611498");
            //2. Create a Statement
            String sql = "insert into cadet values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement myStmt = myConn.prepareStatement(sql);
            //3. Execute SQL query
            myStmt.setString(1, cdtName.getText());
            myStmt.setInt(2, Integer.parseInt(cdtStipend.getText()));
            myStmt.setInt(3, Integer.parseInt(cdtContract.getText()));
            myStmt.setString(4, cdtMajor.getText());
            myStmt.setInt(5, Integer.parseInt(cdtGradYear.getText()));
            myStmt.setInt(6, Integer.parseInt(cdtMilHistory.getText()));
            myStmt.setInt(7, Integer.parseInt(cdtAPFT.getText()));
            myStmt.setInt(8, Integer.parseInt(cdtHeight.getText()));
            myStmt.setInt(9, Integer.parseInt(cdtWeight.getText()));
            myStmt.setInt(10, Integer.parseInt(cdtCWST.getText()));
            myStmt.setInt(11, Integer.parseInt(cdtClearance.getText()));
            myStmt.setInt(12, Integer.parseInt(cdtCAC.getText()));
            myStmt.setInt(13, Integer.parseInt(cdtTags.getText()));
            myStmt.setInt(14, Integer.parseInt(cdtAviation.getText()));
            
            // execute insert SQL stetement
            myStmt.executeUpdate();
        }
        catch (Exception exc) { 
           exc.printStackTrace();
        }
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBparametric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBparametric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBparametric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBparametric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBparametric().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JTextField cdtAPFT;
    private javax.swing.JCheckBox cdtAviation;
    private javax.swing.JCheckBox cdtCAC;
    private javax.swing.JCheckBox cdtCWST;
    private javax.swing.JCheckBox cdtClearance;
    private javax.swing.JCheckBox cdtContract;
    private javax.swing.JTextField cdtGradYear;
    private javax.swing.JTextField cdtHeight;
    private javax.swing.JTextField cdtMajor;
    private javax.swing.JCheckBox cdtMilHistory;
    private javax.swing.JTextField cdtName;
    private javax.swing.JTextField cdtStipend;
    private javax.swing.JCheckBox cdtTags;
    private javax.swing.JTextField cdtWeight;
    private javax.swing.JLabel parametric;
    // End of variables declaration//GEN-END:variables
}
